version: '3.8'

services:

  postgresql:
    image:              postgres:14.1-alpine
    restart:            always
    container_name:     postgresql
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      - /home/ubuntu/environment/datos/postgresql:/var/lib/postgresql/data

  admin:
    image: adminer
    restart: always
    depends_on: 
      - postgresql
    ports:
      - 8081:8080