version: '3.7'

services:
  ftp:
      container_name: ftp-server
      image: garethflowers/ftp-server
      environment:
        - FTP_USER=usuario
        - FTP_PASS=password
      restart: always
      ports:
        - '20-21:20-21/tcp'
        - '40000-40009:40000-40009/tcp'   # passive mode
      volumes:
          - /home/ubuntu/environment/datos/ftp:/home/usuario/shared

# docker compose up -d